### ISSUE TITLE
Project description doesn't appear in project description div

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/vue-pybossa-frontend#139]
I'd expected to see project descriptions to appear under the project title on the RHS, but they're appearing in a floating box when you mouseover the project title.

**Comment by alexandermendes** [comment]
You mean the category descriptions I suppose. So that was a design decision to try and squeeze everything in and bring the actual projects further up the page (in the previous version we had it as a normal block of text but this got in the way). There's quite a lot of text there, not sure where to put it (especially once we have 20 categories)!

**Comment by alexandermendes** [comment]
The other option is to go for something like this, where the description expands if the category is selected.

![image](https://user-images.githubusercontent.com/5636273/29369343-42aebc56-829a-11e7-9388-0ebc0eb415d8.png)

**Comment by alexandermendes** [comment]
(which is probably the kind of thing you meant)

**Comment by mialondon** [comment]
For now let's go for the low-tech method of dividing the text up between tasks for a particular project.
