### ISSUE TITLE
Fix Z39.50 Presenter according to Convert-a-card feedback

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/vue-pybossa-frontend#236]
Thanks to Yongjing‏ https://twitter.com/ge_aimee https://twitter.com/ge_aimee/status/906091923693293569: 
'Wonder if you need feedback on the card project. Great new layout. Keywords remain in the search box for previous records after submission.'

**Comment by alexandermendes** [comment]
Should take a few mins.

**Comment by alexandermendes** [comment]
I'm actually using this one to address a few other comments we had re usability issues for these tasks.
- Layout of the search results compacted
- Link to the Worldcat record added
- Comments box moved to a more obvious collapse button

**Comment by mialondon** [comment]
@alexandermendes could we ask the person who suggested it to review? I don't know the cards project well enough to spot any issues.

**Comment by alexandermendes** [comment]
Well a lot of them came from Bill and I added in a few things I had spotted while I was at it, so that might be a bit tricky as we probably don't want to make a habit of giving outside access to our staging server...

We could say I'll try and get more feedback once they're live and we can always raise a new issue after that if more things come up.
